using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: AssemblyCompanyAttribute("http://netcommon.sourceforge.net/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2006-2011 the Common Infrastructure Libraries Team.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("2.0.0.4527")]
[assembly: AssemblyConfigurationAttribute("net-4.0.win32; dev")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.4527; net-4.0.win32; dev")]
[assembly: AssemblyDelaySignAttribute(false)]

